"""empty message

Revision ID: 3d56f1992224
Revises: 
Create Date: 2024-03-17 16:25:51.195276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as sau

from src import STATUS_CHOICES


# revision identifiers, used by Alembic.
revision: str = '3d56f1992224'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sau.types.choice.ChoiceType(STATUS_CHOICES), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funnel')
    # ### end Alembic commands ###
